<a href="https://colab.research.google.com/github/saurabhpsd/Main1/blob/main/My_prog1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
import matplotlib as mpl
import pandas as pd

dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
print(X)
print(Y)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking care of missing values

In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
Encoding the independent variable

In [6]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X =np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding the dependent variable


In [7]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)
print(Y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into train and test sets

In [8]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size =0.2, random_state =1)

In [9]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [10]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [11]:
print(Y_train)

[0 1 0 0 1 1 0 1]


In [12]:
print(Y_test)

[0 1]


Feature Scaling

In [25]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,3:] = sc.fit_transform
(X_train[:,3:])
X_test[:,3:] = sc.transform
(X_test[:,3:])
print(X_train)
print(X_test)

[[0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 1.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [1.0 0.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 0.0 1.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [1.0 0.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound method TransformerMixin.fit_transform of StandardScaler()>]
 [0.0 1.0 0.0
  <bound method TransformerMixin.fit_transform of StandardScaler()>
  <bound met